name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit, mobile-chrome, mobile-safari]
        include:
          - project: mobile-chrome
            playwright-project: mobile chrome
          - project: mobile-safari
            playwright-project: mobile safari
          - project: chromium
            playwright-project: chromium
          - project: firefox
            playwright-project: firefox
          - project: webkit
            playwright-project: webkit
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      working-directory: ui-tests
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ui-tests
    - name: Run Playwright tests (${{ matrix.project }})
      run: npx playwright test --project="${{ matrix.playwright-project }}"
      working-directory: ui-tests
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.project }}
        path: ui-tests/playwright-report/
        retention-days: 30
